### PR TITLE
Borntodostuff prismarine enhancements

### PR DESCRIPTION
**Pull request by BornToDoStuff**
I have added a significant amount of connected textures and tiling to prismarine-type blocks and decided it should move to its own pull request since its a whole topic on its own.

### CODE REVIEW

**Comment by BornToDoStuff** [comment]
Here are some examples of the vertical tiling for prismarine_bricks, variation of dark_prismarine, and connections for both prismarine and prismarine_bricks.

**Comment by BornToDoStuff** [comment]
Some screenshots of an ocean monument with these prismarine enhancements

**Comment by xalixilax** [comment]
I will not be including this in the default pack. It get a bit too far from default texture but I do think it look nice. I will make a repo really soon just for it

**Comment by xalixilax** [comment]
@BornToDoStuff Created the new repo [there]( https://github.com/xalixilax/xali-s-community-addon-16x)

**Comment by BornToDoStuff** [comment]
Fair enough, I want to respect your vision for the resource pack. Can I ask for a little more information on what pushed it over the edge for you? I have interest in potentially making more changes in the future and want to know where the line is so at the least I can push it towards the right repo if not keep everything "within bounds"

**Comment by xalixilax** [comment]
When you see a block I want to know exactly what is it. I always saw my pack as a pack for someone who don't love them. I never used texture pack since I don't like how it often look out of place with the game and change too much what we are used to. It might also be because I've played Minecraft since November 2010 and got so used to what we have. Prismarine is a block I've tried in the past and always felt a bit off to me.

**Comment by BornToDoStuff** [comment]
I am also a pretty big proponent of vanilla, I usually use only vanilla tweaks so I was excited to find a pack that felt "right" to me. 
I always felt like prismarine got dealt a dirty hand though haha. From your description I am going to try and guess which parts of the prismarine changes I made would be acceptable. Once again: just trying to understand what direction to go with any changes I do, let me know if I am too far off.

1) literally just prismarine but combining, 5/5
2) a good tiling effect for half slabs and stairs using parts of original textures but looks similar to copper, 2/5
3) vertical tiling double half slabs: also using recognizable colors/textures but flipped and cut, notably less vanilla, 2/5
4) looks like a slab but flipped, potential for confusion, 3/5
5) uses cut/paste original texture and tiles but doesnt fit with the vision, 1/5
6) slight alteration to vanilla for tiling purposes but is easily recognizable 4/5
7) relatively simple overlays that use parts of the vanilla texture but when combined heavily could be confusing, 3/5
8) tiles nicely using close-to-vanilla but if only this side is seen, could cause confusion, 3/5
9) deviates slightly but should just be viewed as variation, 4/5
10) fits right in as variation, no confusion caused, 5/5

And is the assumption of "it must be at least 4/5 to be enhanced vanilla" correct?
image
image

**Comment by xalixilax** [comment]
I'd say you are about right. My issue with 6 is the way I see the texture. I see it as scale while having a look like this look more like a patttern. There is also the line that to me look too straight and is a bit out of place. 

10 could easily be included in the pack but 9 might make it look less clean. This could be a creat choice for underwater ruin in oceans since this would make a bit more sense. I would fit perfectly in river and pond for oceans and river below lvl 3. 

While I love 8 and 5, is a good idea, i'd have to make sure big scale how this look. I could also be possible to make the pattern match with lines on the side. So maybe 5 on top and custom texture for bottom that match with lines. Or not sure. I'd have to take a look at it firt

 Nothing wrong with 3  but i'd like to see it used in a build. 

7 I think is just ok. The top part  really don't match with the vanilla look to me. 2 and 4 i'm not 100% sure what was changed lol

**Comment by BornToDoStuff** [comment]
2: The default prismarine_brick stairs are honestly just atrocious and it clips with itself everywhere. This is genuinely my first time doing any work in a texturepack at all, let alone with ctm so I tried to improve the texture while keeping the "scale" but after like two hours I couldnt do it so I just replaced it with squares (which is still somehow better than the original imo).

4: This is a double half slab when its solo so in `method=vertical` its state 3, compared to 3: where its stacked (state 0,1,2)

5 and 8: is done specifically to match the lines actually. 5 is a cross because then the lines coming from each side tile instead of going into a nonsensical texture and 8 is connecting the lines on a diagonal instead of straight across like 5 because I thought a # shape on the bottom would look silly and out of place.

I might give this one another shot next week and go for more of a scales angle since I always saw prismarine_bricks as a poorly executed pattern rather than scales and I like that direction.

**Comment by BornToDoStuff** [comment]
How about something like this instead?
image

**Comment by BornToDoStuff** [comment]
How about something more like this?

prismarine_bricks_preview

**Comment by xalixilax** [comment]
I really like it, but I still think it is too different from the base texture. I think 5 and 8 is just because of how i see it

**Comment by BornToDoStuff** [comment]
Yeah its really unfortunate that the base texture is... really bad, and it doesnt tile at all? They didnt even try to make it tileable, they just put a border on it so they dont have to think about it.
Because I dont disagree it looks pretty different from base texture but it literally has the base texture in it, almost entirely unchanged except removing the border. Then after removing the borders I add I think... 13 pixels per block on this version, of a color that already exists.
I will just submit it to the community repo, because I do think prismarine_bricks should be more usable than they are in vanilla lol.

image

**Comment by xalixilax** [comment]
I think this entire line of blocks should just be an addon by themself since they could look so much better, but with Enhanced Vanilla I really don't want to change the base game as much as I can. One day I'll do a pack with more significant change but for now I have no time for this.

**Pull request closed without merging**
